CREATE TABLE STUDENTS_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    ACTION_TYPE VARCHAR2(10),
    GROUP_NAME VARCHAR2(100),
    STUDENT_ID NUMBER,
    NAME VARCHAR2(100),
    GROUP_ID NUMBER,
    OLD_NAME VARCHAR2(100),
    OLD_GROUP_ID NUMBER,
    TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP
);