INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Petr', 2);

UPDATE STUDENTS
SET NAME = 'Eugene', GROUP_ID = 2
WHERE NAME = 'Petr' AND GROUP_ID = 2;

DELETE FROM STUDENTS
WHERE NAME = 'Eugene' AND GROUP_ID = 2;

SELECT * FROM STUDENTS_LOG