INSERT INTO GROUPS (NAME, C_VAL) VALUES ('Group A', 0);
INSERT INTO GROUPS (NAME, C_VAL) VALUES ('Group B', 0);

INSERT INTO GROUPS (NAME, C_VAL) VALUES ('Group A', 0);

INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Alex', 1);
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Ivan', 2);

INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (1, 'Alice Smith', 1);